services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin21
      POSTGRES_DB: access_cloude
    ports:
      - 5431:5432
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    image: access
    container_name: app
    environment:
      DATABASE_URL: postgres://postgres:admin21@db:5432/access_cloude
    ports:
      - 8081:8081
    depends_on:
      - db
    networks:
      - app-network
networks:
  app-network:
